name: welcome_port
description: "Welcome Port - A Flutter transportation app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  connectivity_plus: ^5.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  package_info_plus: ^9.0.0
  dartz: ^0.10.1
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.2.1
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  jwt_decode: ^0.3.1
  flutter_intl_phone_field: ^0.0.7
  onesignal_flutter: ^5.3.4
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0
  html: ^0.15.5
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  table_calendar: ^3.1.2
  google_maps_flutter: ^2.13.1
  facebook_app_events: ^0.20.1
  salesiq_mobilisten: ^6.5.3
  salesiq_mobilisten_calls: ^0.0.3
  webview_flutter: ^4.13.0
  lottie: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.jpeg"
  adaptive_icon_foreground: "assets/logos/logo.jpeg"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/icons/
    - shorebird.yaml
